bookhub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "", TemplateView.as_view(template_name="base_generic.html"), name="base_generic"
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/login/", include("django.contrib.auth.urls")),
    path("accounts/logout/", include("django.contrib.auth.urls")),
    path("users", include("interfaces.urls")),
]

interfaces/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("hub/", views.BookListView.as_view(), name="hub"),
    path("hub/book/<int:pk>/", views.BookDetailView.as_view(), name="book-detail"),
    path("mybooks/", views.UserBorrowedBooksView.as_view(), name="user-books"),
    path("all-borrowed/", views.AllBorrowedBooksView.as_view(), name="all-borrowed"),
    path("hub/book/<uuid:copy_num>/borrow", views.BorrowView, name="borrow"),
    path("book/<uuid:copy_num>/return", views.ReturnView, name="return"),
    # path("book/<uuid:copy_num>/reserve", views.ReturnView, name="reserve"),
    # path("book/<uuid:copy_num>/maintain", views.ReturnView, name="maintain"),
]

accounts/models.py
from django.db import models

interfaces/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
import datetime


class Genre(models.Model):
    """A model to represent the different book genres"""

    name = models.TextField(max_length=50, help_text="Enter a genre.")

    def __str__(self):
        return self.name


class Book(models.Model):
    """This represents the books that will be in the library"""

    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    blurb = models.TextField(
        max_length=2000, help_text="Enter a brief summary of the book."
    )
    genre = models.ManyToManyField(
        "Genre",
        help_text="Select a genre for this book",
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        """Return a string for the genre so it can display it on the admin site"""
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"


class Author(models.Model):
    """A model for the authors of the books in the library"""

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    class Meta:
        ordering = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])


# def due_back_date():
#     # Users will have to return the book after 5 days
#     return datetime.datetime.today() + datetime.timedelta(days=5)


class BookCopy(models.Model):
    """A model for specific copies of books that will be borrowed from the library."""

    copy_num = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="The unique identification for this book in the whole library.",
    )
    book = models.ForeignKey("Book", on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(
        max_length=100, help_text="Enter the name(alias) of the publishing company"
    )
    borrow_date = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    due_back = models.DateField(null=True, blank=True)

    possible_statuses = (
        ("r", "RESERVED"),
        ("a", "AVAILABLE"),
        ("b", "BORROWED"),
        ("w", "BEING WORKED ON"),
    )
    status = models.CharField(
        max_length=1,
        choices=possible_statuses,
        blank=True,
        null=True,
        default="a",
        help_text="Availability status",
    )

    def fine(self):
        if self.status == "b":
            days_overdue = 0
            days_overdue = datetime.date.today() - self.due_back

            days_overdue = days_overdue.days
            if days_overdue <= 0:
                return 0
            elif days_overdue <= 3:
                return 3000
            elif days_overdue > 3:
                return 10000

    def __str__(self):
        return f"{self.copy_num} ({self.book.title})"

    class Meta:
        verbose_name_plural = "Book Copies"
        permissions = (("can_mark_as_returned", "Can set book as returned"),)

accounts/views.py
from django.shortcuts import render

# Create your views here.

interfaces/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Book, BookCopy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime


class BookListView(generic.ListView):
    model = Book
    context_object_name = "book_list"
    template_name = "interfaces/hub.html"
    ordering = ["title"]
    # paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


class UserBorrowedBooksView(LoginRequiredMixin, generic.ListView):
    """This will let users see books they have borrowed"""

    model = BookCopy
    template_name = "interfaces/user-books.html"
    context_object_name = "borrowed_list"

    def get_queryset(self):
        return (
            BookCopy.objects.filter(borrower=self.request.user)
            .filter(status__exact="b")
            .order_by("due_back")
        )


class AllBorrowedBooksView(PermissionRequiredMixin, generic.ListView):
    """This is for borrowed books that will be seen by the librarian"""

    model = BookCopy
    template_name = "interfaces/all-borrowed.html"
    context_object_name = "borrowed_list"
    permission_required = "interfaces.can_mark_as_returned"

    def get_queryset(self):
        return BookCopy.objects.filter(status__exact="b").order_by("due_back")


def BorrowView(request, copy_num):
    """For borrowing books"""
    book_copy_borrow = get_object_or_404(BookCopy, pk=copy_num)
    book_copy_borrow.borrow_date = datetime.date.today()
    # book_copy_borrow.due_back = datetime.date.strftime(due_back_date, "%d/%m/%y")
    book_copy_borrow.due_back = book_copy_borrow.borrow_date + datetime.timedelta(
        days=5
    )
    book_copy_borrow.borrower = request.user
    book_copy_borrow.status = "b"
    book_copy_borrow.save()
    return HttpResponseRedirect(reverse("user-books"))


def ReturnView(request, copy_num):
    """For returning borrowed books"""
    book_copy_return = get_object_or_404(BookCopy, pk=copy_num)
    book_copy_return.borrow_date = None
    book_copy_return.due_back = None
    book_copy_return.borrower = None
    book_copy_return.status = "a"
    book_copy_return.save()
    return render(request, "interfaces/all-borrowed.html", {"copy": book_copy_return})


# def ReserveView(request, copy_num):
#     book_copy_reserve = get_object_or_404(BookCopy, pk=copy_num)
#     book_copy_reserve.borrow_date = None
#     book_copy_reserve.borrower = None
#     book_copy_reserve.status = "r"
#     book_copy_reserve.save()
#     return render(request, "interfaces/all-borrowed.html", {"copy": book_copy_return})


# def WorkingView(request, copy_num):
#     book_copy_working = get_object_or_404(BookCopy, pk=copy_num)
#     book_copy_working.borrow_date = None
#     book_copy_working.borrower = None
#     book_copy_working.status = "w"
#     book_copy_working.save()
#     return render(request, "interfaces/all-borrowed.html")

accounts/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Book Hub</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'hub' %}">All books</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'all-borrowed' %}">All Borrowed Books</a></li>
          <li><a href="{% url 'user-books' %}">My Borrowed Books</a></li>
          <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
          <li>User: {{ user.get_username }}</li>
          {% else %}
          <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
          {% endif %}
        </ul>
        </ul>
        {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>

</html>

interfaces/templates/interfaces/all-borrowed.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        h1 {
            font-family: Courier;
        }

        p {
            font-family: Courier;
        }

        a:link {
            color: rgb(11, 75, 75);
            text-decoration: none;
            background-color: none;
        }

        a:visited {
            color: rgb(11, 75, 75);
            text-decoration: none;
            background-color: none;
        }

        a:hover {
            color: grey;
            text-decoration: underline;
            background-color: none
        }

        table,
        th,
        td {
            border: 1px solid whitesmoke;
            border-collapse: collapse;
            text-align: center;
            padding: 5px;
        }

        tr:nth-child(even) {
            background-color: lightgrey;
        }
    </style>
    <title>All Borrowed Books</title>
</head>

<body>
    {% if borrowed_list %}
    <h1>All Borrowed Books</h1>
    <table>
        <tr>
            <th>Book</th>
            <th>Borrower</th>
            <th>Due Date</th>
            <th>Fine</th>
            <th>Return</th>
        </tr>
        {% for copy in borrowed_list %}
        <tr>
            <td>
                <a href="{% url 'book-detail' copy.book.pk %}">
                    {{ copy.book.title }}
                </a>
            </td>
            <td>
                {{ copy.borrower }}
            </td>
            <td>
                {{ copy.due_back }}
            </td>
            <td>
                {{ copy.fine }}
            </td>
            <td>
                <a href="{% url 'return' copy.copy_num %}">Return</a>
            </td>
        </tr>
        {% endfor %}
        <table>
            {% else %}
            <h2>No borrowed books</h2>
            {% endif %}
            <h3>Click here to checkout <a href="{% url 'base_generic' %}">other pages</a></h3>
</body>

</html>

interfaces/templates/interfaces/book_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{{ book.title }}</title>
</head>

<body>
    <h1>{{ book.title }}</h1>
    <h2>{{book.author}}</h2>
    <p><strong>Summary</strong></p>
    {{ book.blurb }}
    <p><strong>Genre</strong></p>
    {{ book.genre.all|join:"_" }}
    {% if user.is_authenticated %}
    {% else %}
    <h4 style="color:rgb(11, 75, 75)">A <a href="{%url 'login' %}?next={{request.path}}">login</a> is required to
        borrow the books</h4>
    {% endif %}
    <h2>Copies</h2>
    {%for copy in book.bookcopy_set.all%}
    <p><strong>{{copy.get_status_display}}</p></strong>
    {%if copy.status == 'a'%}
    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'borrow' copy.copy_num %}">
        {% csrf_token %}
        <button type="submit" class="button">BORROW</button>
    </form>
    {% endif %}
    {% elif copy.status == 'b'%}
    <p><strong>Due to be returned: {{copy.due_back}}</strong></p>
    {% endif %}
    <p>Id: {{ copy.copy_num }}</p>
    <p>Imprint: {{ copy.imprint }}</p>
    {% endfor %}
    <h3>Click here to checkout <a href="{% url 'base_generic' %}">other pages</a></h3>
</body>

</html>

interfaces/templates/interfaces/hub.html
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        h1 {
            font-family: Courier;
        }

        p {
            font-family: Courier;
        }

        a:link {
            color: rgb(11, 75, 75);
            text-decoration: none;
            background-color: none;
        }

        a:visited {
            color: rgb(11, 75, 75);
            text-decoration: none;
            background-color: none;
        }

        a:hover {
            color: grey;
            text-decoration: underline;
            background-color: none
        }
    </style>
    <title>Hub</title>
</head>

<body>
    <div style="background-color: rgb(11,75, 75);padding:2px;color:whitesmoke;">
        <h1 style="text-align:left;margin-left:10px;">Book List</h1>
    </div>
    <h3>Click here to checkout <a href="{% url 'base_generic' %}">other pages</a></h3>
    {% if book_list %}
    <dl>
        {% for book in book_list %}
        <dt>
            <a href="{{ book.get_absolute_url }}">
                <h2 title=" {{ book.author }} ">{{ book.title }}
                </h2>
                <! when you hover it will show the author>
            </a>
        <dd>{{ book.blurb }}</dd>
        </dt>
        {% endfor %}
    </dl>
    {% else %}
    <p>There is no book in the library.</p>
    {% endif %}

</body>

</html>

interfaces/templates/interfaces/user-books.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        h1 {
            font-family: Courier;
        }

        p {
            font-family: Courier;
        }

        a:link {
            color: rgb(11, 75, 75);
            text-decoration: none;
            background-color: none;
        }

        a:visited {
            color: rgb(11, 75, 75);
            text-decoration: none;
            background-color: none;
        }

        a:hover {
            color: grey;
            text-decoration: underline;
            background-color: none
        }

        table,
        th,
        td {
            border: 1px solid whitesmoke;
            border-collapse: collapse;
            text-align: center;
            padding: 5px;
        }

        tr:nth-child(even) {
            background-color: lightgrey;
        }
    </style>
    <title>My Borrowed books</title>
</head>

<body>
    <h1>My Borrowed Books</h1>
    {% if borrowed_list %}
    <table style="width:60%">
        <tr>
            <th>Book</th>
            <th>Due Date</th>
            <th>Fine</th>
        </tr>
        {% for copy in borrowed_list %}
        <tr>
            <td>
                <a href="{% url 'book-detail' copy.book.pk %}">
                    {{ copy.book.title }}
                </a>
            </td>
            <td>
                {{ copy.due_back }}
            </td>
            <td>
                {{copy.fine}}
            </td>
        </tr>
        {% endfor %}
        <table>
            {% else %}
            <p>You have not borrowed any books.</p>
            {% endif %}
            <h2>Click here to return to the <a href="{% url 'hub' %}"> home page.</a></h2>
            <h3>Click here to checkout <a href="{% url 'base_generic' %}">other pages</a></h3>

</body>

</html>